#!/usr/bin/env python3
# vim: set et ts=4 sw=4 sts=4:

import sys
import os
import subprocess
import sqlite3

CONFIG = {
    'beets db': '/media/nastynas/homes/bart/.config/beets/library.db',
}

if __name__ == '__main__':
    conn = sqlite3.connect(CONFIG['beets db'])
    c = conn.cursor()
    c.execute('''
        delete from items
        where path like ''
    ''')
    conn.commit()
